### ISSUE TITLE
crash when trying to grant access to shizuku on android 14

### ISSUE THREAD

**Issue by shak38** [timschneeb/RootlessJamesDSP#232]
[Error in RootlessJamesDSP 5757530cf133.txt](https://github.com/user-attachments/files/16258060/Error.in.RootlessJamesDSP.5757530cf133.txt)

```
type: crash
osVersion: google/shiba/shiba:14/AP2A.240705.005/2024071200:user/release-keys
package: me.timschneeberger.rootlessjamesdsp:45
process: me.timschneeberger.rootlessjamesdsp
processUptime: 6717 + 231 ms
installer: com.android.packageinstaller

java.lang.NoSuchMethodError: No interface method grantRuntimePermission(Ljava/lang/String;Ljava/lang/String;I)V in class Landroid/permission/IPermissionManager; or its super classes (declaration of 'android.permission.IPermissionManager' appears in /system/framework/framework.jar!classes3.dex)
	at me.timschneeberger.hiddenapi_impl.ShizukuSystemServerApi.PermissionManager_grantRuntimePermission(ShizukuSystemServerApi.java:54)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment.ensureDumpPermission(OnboardingFragment.kt:487)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment.canAccessNextPage(OnboardingFragment.kt:463)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment.changePage(OnboardingFragment.kt:426)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment.changePage$default(OnboardingFragment.kt:419)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment$onViewCreated$8.invoke(OnboardingFragment.kt:250)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment$onViewCreated$8.invoke(OnboardingFragment.kt:222)
	at me.timschneeberger.rootlessjamesdsp.view.Card._init_$lambda$1(Card.kt:133)
	at me.timschneeberger.rootlessjamesdsp.view.Card.$r8$lambda$O4AgqJI0zQIWi33ObcCsXniNjEY(Unknown Source:0)
	at me.timschneeberger.rootlessjamesdsp.view.Card$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7931)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1211)
	at android.view.View.performClickInternal(View.java:7908)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30990)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

In the latest build
Thanks

**Comment by AndnixSH** [comment]
Same issue on my Pixel 8 Pro running Android 14

**Comment by kquote03** [comment]
As a workaround for anyone else reading this you can just run the adb commands using aShell instead

**Comment by Laserology** [comment]
Please fix this, it is a major inconvenience.

**Comment by SteadyStatus21** [comment]
Same on Google Pixel 8 Pro, Android 15 Beta 4.2, (AP31.240617.015):
```
FATAL EXCEPTION: main
Process: me.timschneeberger.rootlessjamesdsp, PID: 484
java.lang.NoSuchMethodError: No interface method grantRuntimePermission(Ljava/lang/String;Ljava/lang/String;I)V in class Landroid/permission/IPermissionManager; or its super classes (declaration of 'android.permission.IPermissionManager' appears in /system/framework/framework.jar!classes3.dex)
	at me.timschneeberger.hiddenapi_impl.ShizukuSystemServerApi.PermissionManager_grantRuntimePermission(ShizukuSystemServerApi.java:49)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment.ensureDumpPermission(OnboardingFragment.kt:487)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment.canAccessNextPage(OnboardingFragment.kt:463)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment.changePage(OnboardingFragment.kt:426)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment.changePage$default(OnboardingFragment.kt:419)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment$onViewCreated$8.invoke(OnboardingFragment.kt:250)
	at me.timschneeberger.rootlessjamesdsp.fragment.OnboardingFragment$onViewCreated$8.invoke(OnboardingFragment.kt:222)
	at me.timschneeberger.rootlessjamesdsp.view.Card._init_$lambda$1(Card.kt:133)
	at me.timschneeberger.rootlessjamesdsp.view.Card.$r8$lambda$O4AgqJI0zQIWi33ObcCsXniNjEY(Unknown Source:0)
	at me.timschneeberger.rootlessjamesdsp.view.Card$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:8028)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1211)
	at android.view.View.performClickInternal(View.java:8005)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31229)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
```

**Comment by bezaleelmfg** [comment]
Same on Pixel 9Pro XL.

**Comment by asmbk** [comment]
Same on Pixel 8, Android 14 and 15

**Comment by matthius7** [comment]
Thread 'Jamesdsp rootless (working p9 pro)' https://xdaforums.com/t/jamesdsp-rootless-working-p9-pro.4701607/
I made this thread with info I collected. I'm using Jamesdsp rootless on a new pixel 9 pro and it's amazing.
